# SELECT DATE_FORMAT(START_DATE, '%c') AS MONTH, CAR_ID, count(*) as RECORDS
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY
# where START_DATE between '2022-08-01' and '2022-10-31'
# group by MONTH, CAR_ID
# having count(*) >= 5
# order by MONTH, CAR_ID DESC;

WITH RentalCars AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
select MONTH(START_DATE) AS MONTH, CAR_ID, count(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
where CAR_ID in (select CAR_ID from RentalCars) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;